




# Combine U.S. Presidents with Global Regimes
# Full list will include prior U.S. entries and the global/historical ones
regimes_extended = [
    ("George Washington", 18, +1, 4, 3.5, "The Gentleman-General Who Declined the Crown"),
    ("John Adams", 30, +1.5, 3, 4, "Centralizer of fragile federal authority"),
    ("Thomas Jefferson", 28, -1.5, 3.5, 3.5, "Libertarian vision with enslaved foundations"),
    ("James Madison", 26, 0, 3, 3.5, "Scholar of the Constitution under wartime stress"),
    ("James Monroe", 25, +0.5, 2.5, 3, "Quiet expansionist with a doctrine"),
    ("John Quincy Adams", 27, +0.5, 2, 3.5, "Technocrat of national improvement"),
    ("Andrew Jackson", 62, +5.5, 6, 6.5, "Populist strongman with a trail of tears"),
    ("Abraham Lincoln", 59, -3, 6.5, 4.5, "Crisis autocrat in defense of union and abolition"),
    ("William H. Taft", 33, +1, 2, 3.5, "Legalist institutionalist with restrained hand"),
    ("Dwight D. Eisenhower", 38, +2.5, 2.5, 4, "Quiet empire manager with military poise"),
    ("John F. Kennedy", 36, -1.5, 3.5, 4.5, "Liberal Cold War charisma with covert fire"),
    ("Richard Nixon", 60, +2, 4, 7, "Law-and-order authoritarianism with paranoia core"),
    ("Ronald Reagan", 48, +3.5, 3.5, 6, "Smiling deregulator with a carceral shadow"),
    ("George H. W. Bush", 38, +1.5, 2, 4.5, "Cold realism under a velvet glove"),
    ("Bill Clinton", 41, +1, 2.5, 5.5, "Centrist neoliberalism with mass incarceration edge"),
    ("George W. Bush", 55, +4, 6, 6.5, "Post-9/11 executive expansion with evangelical overtone"),
    ("Barack Obama", 44, -0.5, 2.5, 5.5, "Technocratic optimism with drone-era contradictions"),
    ("Donald Trump (2016–2020)", 64, +6.5, 4, 7.5, "Authoritarian populism in chaotic packaging"),
    ("Joe Biden", 43, +1.5, 1.5, 6.5, "Technocratic liberalism under pressure"),
    ("Donald Trump (2024 projected)", 81, +7.5, 5.5, 8.5, "Vengeance with a Legal Pad"),
    ("FDR (1933–1945)", 52, -4, 5, 3, "Crisis-centralizer with constitutional brakes"),
    ("Modi (India)", 68, +7, 6.5, 7.5, "Democracy with a Saffron Spine"),
    ("Peter Thiel (hypothetical)", 91, +7.5, 6.5, 9, "Technocratic monarchy with a god complex"),
    ("AOC (hypothetical)", 58, -7.5, 2.5, 6.5, "Moral absolutism with a climate budget"),
    ("Steve Bannon (hypothetical)", 87, +9, 6.5, 9, "Traditionalist insurrectional governance"),
    ("Lenin (1917–1924)", 85, -9, 7.5, 7, "Ideological steel forged into party rule"),
    ("Caligula", 78, +6.5, 6.5, 8, "Divine chaos with a knife"),
    ("Genghis Khan", 96.4, +5, 10, 2, "Statistical annihilation with postal service"),
    ("Henry VII (Tudor)", 67, +3, 4.5, 6, "Accountant-king with velvet tyranny"),
    ("Macron (2017–2025)", 40, +1, 1.5, 5.5, "Technocrat under street revolt"),
    ("Taliban (2021–2025)", 91, +8, 9, 2, "Clerical militarism with gender apartheid"),
    ("ISIL (2014–2019)", 99.1, +9, 10, 0.5, "Theofascist genocidal terror state"),
    ("FDR (1933–1945)", 52, -4, 5, 3, "Crisis-centralizer with constitutional brakes"),
    ("Airstrip One (1984)", 100, -1, 10, 0, "Total surveillance, total mind control"),
    ("Panem (fictional)", 92.7, +8, 10, 4, "Spectacle-based oligarchic dystopia"),
    ("Stalin (1937)", 89.1, -9, 9, 2, "Totalitarian terror forged in ideology"),
    ("Franco (1939–75)", 85.5, +9, 7.5, 3, "Clerical fascist authoritarian stability"),
    ("Putin (2023)", 81.8, +5, 7, 6.5, "Autocratic kleptocracy with revanchist bite"),
    ("Orbán (2023)", 64.5, +6.5, 3.5, 5, "Elected illiberalism in the EU's backyard"),
    ("Erdogan (2023)", 70.0, +6, 5, 5, "Islamist-nationalist soft authoritarianism"),
    ("Donald Tusk (Poland)", 42, +1.5, 2, 4, "Liberal democratic centrist against authoritarian tide"),
    ("Margaret Thatcher", 49, +4, 3, 5.5, "Iron neoliberal with protest crackdowns"),
    ("Claudia Sheinbaum (projected)", 44, -2, 2.5, 4.5, "Technocratic progressive with populist roots"),
    ("Justin Trudeau", 39, -1, 2, 5, "Cosmopolitan liberal with state paternalism"),
    ("Ivan the Terrible", 94, +7, 9, 3, "Tsarist absolutism with sadistic pageantry"),
    ("Kim Jong Un", 100, +10, 10, 0, "Hereditary totalitarian monarchy with nuclear threat"),
    ("Kim Jong Il", 99, +10, 10, 0.5, "Theatrical dynastic oppression with famine"),
    ("Fidel Castro", 82, -8.5, 7, 6.5, "Revolutionary autocrat with educational pride"),
    ("Saddam Hussein", 93, +9, 9.5, 2, "Brutal Ba'athist dictator with regional terror"),
    ("Benito Mussolini", 91, +9.5, 8.5, 2.5, "Corporate fascist and military narcissist"),
    ("Mao Zedong", 96, -9, 10, 2, "Cultic communist with industrial-scale disaster"),
    ("Xi Jinping", 87, -2, 8, 4, "Technocratic Leninism with digital authoritarian edge"),
    ("Volodymyr Zelenskyy", 41, 0, 2.5, 4, "Democratic wartime leader under existential pressure"),
    ("Josip Broz Tito", 68, -2.5, 6, 3.5, "Benevolent strongman balancing East and West"),
    ("Slobodan Milošević", 84, +8.5, 9, 3, "Nationalist demagogue turned war criminal"),
    ("Adolf Hitler (1939)", 100, +10, 10, 0.5, "Fascist race-state and apex genocidal regime"),
    ("Bernie Sanders (hypothetical)", 52, -6.5, 2.5, 5.5, "Democratic socialist reformism with state activism"),
    ("Pol Pot", 91, -10, 10, 1, "Utopian agrarian genocide and elite extermination"),
    ("Idi Amin", 87, +8.5, 9, 2, "Militarized kleptocracy with ethnic terror"),
    ("Jean-Bédel Bokassa", 88, +9, 9, 2, "Self-declared emperor and cannibalistic kleptocrat"),
    ("Nelson Mandela (1994–1999)", 28, -2.5, 2, 2.5, "Reconciliatory post-apartheid democrat with global moral stature"),
    ("Lech Wałęsa (1990–1995)", 35, -1, 2.5, 3, "Solidarity activist turned democratic president"),
    ("Angela Merkel (2005–2021)", 34, +1, 1.5, 3.5, "Steady centrist stabilizer in the EU era"),
    ("Vaclav Havel (1989–2003)", 26, -2, 1, 2, "Poet-president who brought liberalism to post-Soviet Czechia"),
    ("Jacinda Ardern (2017–2023)", 32, -1, 1.5, 3, "Empathic progressive with crisis-era trust"),
]

import pandas as pd
regimes_extended = pd.DataFrame(regimes_extended, columns=["Regime", "RAI", "IDEO", "HDR", "PBR", "Tagline"])
regimes_extended.to_csv("regime_scores", index=False)